<a href="https://colab.research.google.com/github/dharineeshramtp2000/SVM-Classification-Balance-Scale-/blob/master/Balance_Scale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Libraries

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset. Here we use the dataset from [ML Data](https://www.mldata.io/datasets/).
![](https://cdn3.iconfinder.com/data/icons/market-and-economic/48/69-512.png)
---

Here we predict the class on which way the scale tips.
**Values: L for left tip, B for balance, R for right tip**






In [2]:
Dataset = pd.read_csv("balance_scale_weka_dataset.csv")
X = Dataset.iloc[:,:-1]
y = Dataset.iloc[:,-1]
Dataset.describe()

left_weight  left_distance  right_weight  right_distance
count   625.000000     625.000000    625.000000      625.000000
mean      3.000000       3.000000      3.000000        3.000000
std       1.415346       1.415346      1.415346        1.415346
min       1.000000       1.000000      1.000000        1.000000
25%       2.000000       2.000000      2.000000        2.000000
50%       3.000000       3.000000      3.000000        3.000000
75%       4.000000       4.000000      4.000000        4.000000
max       5.000000       5.000000      5.000000        5.000000

Now lets feature scale our independent variables from our famous [scikit](https://scikit-learn.org/stable/) library

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

Splitting the dataset into training and testing and performing a good shuffle of data

In [0]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(X, y , test_size = 0.3, random_state=0, shuffle =True)

Now lets define our SVM Classification model.
We use the Gaussian Kernel which is most commonly preferred.
Apart from that we define the constant C so that the hyperplane best fits for our train and test data.

![](https://miro.medium.com/max/1400/1*c_JJszZ8GlnQ7kx88Z2TeA.png)

Feel free to use the [Documnetaton for Support Vector Classification](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html)

In [5]:
from sklearn.svm import SVC
classifier = SVC(C = 10.0, kernel = 'rbf',decision_function_shape='onr')
classifier.fit(X_train, y_train)


SVC(C=10.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='onr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

Now lets predict with our test set

In [0]:
y_pred = classifier.predict(X_test)

Its time for evaluating our model.

![](https://www.thinkebiz.net/wp-content/uploads/2018/01/74228032_s.jpg)

---
Lets first predict how our model is fitting for our training set
We use the famous
1.   f1 score
2.   accuracy 
to evaluate the model





In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [9]:
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY ---------------------->",acc_train)
print("F1 SCORE ---------------------->",f1_train)


Traing set results
ACCURACY ----------------------> 0.9794050343249427
F1 SCORE ----------------------> 0.9797582645377477


Now lets see how well is our model. So now lets evaluate with our test set 

In [10]:
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY ---------------------->",acc_test)
print("F1 SCORE ---------------------->",f1_test)

Test set results
ACCURACY ----------------------> 0.9521276595744681
F1 SCORE ----------------------> 0.9533721397029304


Now lets have our famous Confusion Matrix to visually understand.

In [13]:
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[10  0  1]
 [ 2 93  1]
 [ 2  3 76]]


Our model has worked well with our test set too.
The **accuaracy** and **f1 score** for both test and training set is good.
Its always to put a question and ask to ourselves that is this the best model?

---

Obvisouly not!
We can still achive our accuracy by changing our models, changing the independent variables, change the metrics and so on.
Its great that we have successfully implemented SVM classification with our Balacne Scale Dataset.
